### ISSUE TITLE
Ишью с отдела архитектуры, нипа ^^

### ISSUE THREAD

**Issue by kugimiya** [ridouchire/CS-CartPrimeCost#2]
1. Лангвары в `addon.xml` не пишут, для этого есть `var/langs/<lang_code>/addons/<addon>.po`
2. Название и описание аддона тоже в `<addon>.po` задаются

**Comment by ridouchire** [comment]
Хорошо. Т.к. писал по примеру из документации и там этот момент опущен/мною не был отмечен, то и не сделал.

**Comment by ridouchire** [comment]
@kugimiya, прошу отпиздить за ошибки.

**Comment by kugimiya** [comment]
В po-файле там все норм, можешь крыть.
