### ISSUE TITLE
Перевод на остальные языки.

### ISSUE THREAD

**Issue by ridouchire** [ridouchire/CS-CartPrimeCost#3]
Сабж.

**Comment by kugimiya** [comment]
`var/langs/<lang_name>/addons/<addon>.po`

**Comment by kugimiya** [comment]
https://www.cs-cart.ru/docs/4.7.x/developer_guide/core/language_variables.html

**Comment by ridouchire** [comment]
Да, спасибо. Мне известно.

**Comment by ridouchire** [comment]
В целом, раз уж техписатели и прочие кирпичи, то перевода на `en` и `ru` должно хватить.

**Comment by ridouchire** [comment]
В общем, выполнено.
